[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "bananinhamj", email = "viliczinskimj@gmail.com"},
]
dependencies = [
    "django>=4.2.1",
    "djangorestframework>=3.14.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
