# Generated by Django 4.1.7 on 2023-03-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_alter_cor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cor',
        ),
    ]
