# Generated by Django 4.1.7 on 2023-03-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0007_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca', to='garagem.marca'),
        ),
    ]
