# Generated by Django 4.1.7 on 2023-05-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0009_alter_acessorio_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
